#spring:
#  devtools:
#    livereload:
#      enabled: true
#    freemaker:
#      cache: false
#
#  datasource:
#    localdb:
#      jdbc-url: jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=yes&characterEncoding=utf-8&serverTimezone=UTC
#      username: root
#      password: 0000
#      driver-class-name: com.mysql.jdbc.Driver
#
#    jpa:
#      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#      properties:
#        hibernate:
#          format_sql: true
#
#    session:
#      store-type: jdbc
#      jdbc:
#        initialize-schema: always
#
#  logging:
#    level:
#      org:
#        hibernate:
#          SQL: DEBUG
#          type:
#            descriptor:
#              sql:
#                BasicBinder: TRACE
#  mybatis:
#    type-aliases-package: kr.co.fastcampus.eatgo
#    mapper-locations: mybatis/mapper/**/*.xml